### ISSUE TITLE
Allow space characters in token and team names

### ISSUE THREAD

**Issue by bensymonds** [davidji99/terraform-provider-rollbar#23]
There's nothing I could see in the API docs for ~[project](https://explorer.docs.rollbar.com/#operation/create-a-project)~ [EDIT: I mean [access token](https://explorer.docs.rollbar.com/#tag/Project-Access-Tokens/paths/~1api~11~1project~1{id}~1access_tokens/post)] or [team](https://explorer.docs.rollbar.com/#operation/create-a-team) (they just say `string`) but based on my experience they can have a space in their name - we have existing tokens/teams containing spaces in our rollbar account.

At the moment in the provider is validating against a regexp which doesn't allow them:

```
^[a-zA-Z][0-9A-Za-z,.\-_]{1,31}$
```

**Comment by bensymonds** [comment]
@davidji99 Ugh sorry I made a typo in my description - I said "project" but meant "access token"! I had noticed that projects _do_ have the restriction. Sorry about causing you to waste your time there a bit.

Otherwise this all sounds good - thanks for the quick response!

**Comment by davidji99** [comment]
No worries @bensymonds !
